### ISSUE TITLE
v1.2.0 File not found index.js

### ISSUE THREAD

**Issue by theowenyoung** [wdzeng/edge-addon#5] opened 2023-08-29 13:02 UTC
Hi, thanks for the great action, it seems that there is an error in v1.2.0: 

Error: File not found: '/home/runner/work/_actions/wdzeng/edge-addon/v1.2.0/index.js'

do you forget some dist files?

**Comment by wdzeng** [comment] 2023-08-29 14:25
Oh I am sorry about this.

**Comment by wdzeng** [comment] 2023-08-30 11:26
The Microsoft API server is responding weird access token. Check if this will be fixed.

**Comment by theowenyoung** [comment] 2023-08-30 12:42
Maybe I'll just have to verify again on the next release, I manually switched to v1.1.0 and it worked fine.

I will re-test v1.2.0 next time I release it, thank you!

**Comment by theowenyoung** [comment] 2023-08-31 16:46
still not work.

![image](https://github.com/wdzeng/edge-addon/assets/62473795/a1f6564d-3ef5-4eb5-b15d-53d2abfbca20)

**Comment by wdzeng** [comment] 2023-08-31 18:34
Hi,

I still received invalid access tokens today. The JWT format I saw is totally wrong. I am contacting Microsoft support center to check if their backend has any problem. Before the issue is solved I plan not to publish a new version.

Please use v1.1 instead. Sorry for the inconvenience.

**Comment by theowenyoung** [comment] 2023-09-02 03:21
Thank you!

I tried v1.1 again, and it didn’t seem to work anymore, and it prompted jwt token invalid. I also tested 2 other actions of the same type, and they had similar problems, so there should be some changes on Microsoft’s side. Just have to wait, thanks again for a great job

**Comment by wdzeng** [comment] 2023-09-02 10:50
I found https://github.com/microsoft/MicrosoftEdge-Extensions/issues/107. Let's wait for it to be fixed.

**Comment by theowenyoung** [comment] 2023-09-04 16:38
It seems that now the API returns normal and I can release normally with V1.1.0

**Comment by wdzeng** [comment] 2023-09-05 16:57
Released v1.2.1. Thanks for your help!

**Closed as completed by wdzeng** 2023-09-05 16:57 UTC
Labels: bug, good first issue
